/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package com.marklogic.gradle.stateconductor

import org.gradle.testfixtures.ProjectBuilder
import org.gradle.api.Project
import spock.lang.Specification

/**
 * A simple unit test for the 'com.marklogic.gradle.stateconductor.greeting' plugin.
 */
public class StateConductorPluginTest extends Specification {
    def "plugin registers task"() {
        given:
        def project = ProjectBuilder.builder().build()

        when:
        project.plugins.apply("com.marklogic.gradle.stateconductor.state-conductor")

        then:
        project.tasks.findByName("greeting") != null
    }
}
